<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Carbon\Carbon;

class CandidatesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('candidates')->insert([
            [
                'email' => 'john.doe@example.com',
                'password' => Hash::make('password123'),
                'name' => 'John Doe',
                'enrollment' => 'ENR001',
                'date_of_registration' => '2023-01-10',
                'phone' => '1234567890',
                'dob' => '1998-05-21',
                'gender' => 'male',
                'school_name' => 'Greenwood High',
                'year' => 2022,
                'session' => 'Morning',
                'address' => '123 Main St',
                'country' => 'USA',
                'state' => 'California',
                'city' => 'Los Angeles',
                'pincode' => '90001',
                'group' => 'A',
                'other_selection' => 'Option1',
                'status' => 'active',
                'created_at' => Carbon::parse('2025-02-01 10:00:00'),
                'updated_at' => Carbon::parse('2025-02-01 10:00:00'),
            ],
            [
                'email' => 'jane.smith@example.com',
                'password' => Hash::make('password123'),
                'name' => 'Jane Smith',
                'enrollment' => 'ENR002',
                'date_of_registration' => '2023-02-15',
                'phone' => '2345678901',
                'dob' => '1997-08-12',
                'gender' => 'female',
                'school_name' => 'Hilltop School',
                'year' => 2021,
                'session' => 'Evening',
                'address' => '456 Oak St',
                'country' => 'USA',
                'state' => 'Texas',
                'city' => 'Dallas',
                'pincode' => '75001',
                'group' => 'B',
                'other_selection' => 'Option2',
                'status' => 'inactive',
                'created_at' => Carbon::parse('2025-02-02 11:00:00'),
                'updated_at' => Carbon::parse('2025-02-02 11:00:00'),
            ],
            [
                'email' => 'mike.jones@example.com',
                'password' => Hash::make('password123'),
                'name' => 'Mike Jones',
                'enrollment' => 'ENR003',
                'date_of_registration' => '2023-03-20',
                'phone' => '3456789012',
                'dob' => '2000-11-05',
                'gender' => 'male',
                'school_name' => 'Sunrise Academy',
                'year' => 2023,
                'session' => 'Afternoon',
                'address' => '789 Pine St',
                'country' => 'Canada',
                'state' => 'Ontario',
                'city' => 'Toronto',
                'pincode' => 'M4B 1B3',
                'group' => 'A',
                'other_selection' => 'Option3',
                'status' => 'active',
                'created_at' => Carbon::parse('2025-02-03 12:00:00'),
                'updated_at' => Carbon::parse('2025-02-03 12:00:00'),
            ],
            [
                'email' => 'susan.lee@example.com',
                'password' => Hash::make('password123'),
                'name' => 'Susan Lee',
                'enrollment' => 'ENR004',
                'date_of_registration' => '2023-04-10',
                'phone' => '4567890123',
                'dob' => '1999-02-25',
                'gender' => 'female',
                'school_name' => 'Maple Leaf School',
                'year' => 2020,
                'session' => 'Morning',
                'address' => '321 Elm St',
                'country' => 'USA',
                'state' => 'New York',
                'city' => 'New York',
                'pincode' => '10001',
                'group' => 'C',
                'other_selection' => 'Option4',
                'status' => 'active',
                'created_at' => Carbon::parse('2025-02-04 09:30:00'),
                'updated_at' => Carbon::parse('2025-02-04 09:30:00'),
            ],
            [
                'email' => 'chris.wilson@example.com',
                'password' => Hash::make('password123'),
                'name' => 'Chris Wilson',
                'enrollment' => 'ENR005',
                'date_of_registration' => '2023-05-05',
                'phone' => '5678901234',
                'dob' => '2001-06-15',
                'gender' => 'male',
                'school_name' => 'Blue Ridge High',
                'year' => 2019,
                'session' => 'Evening',
                'address' => '654 Cedar St',
                'country' => 'UK',
                'state' => 'England',
                'city' => 'London',
                'pincode' => 'EC1A 1BB',
                'group' => 'B',
                'other_selection' => 'Option1',
                'status' => 'inactive',
                'created_at' => Carbon::parse('2025-02-05 10:30:00'),
                'updated_at' => Carbon::parse('2025-02-05 10:30:00'),
            ],
        ]);
    }
}
