<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Carbon\Carbon;

class CandidatesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('candidates')->insert([
            [
                'email' => 'emma.johnson@example.com',
                'password' => Hash::make('password123'),
                'name' => 'Emma Johnson',
                'enrollment' => 'ENR006',
                'date_of_registration' => '2023-06-10',
                'phone' => '6789012345',
                'dob' => '1998-09-10',
                'gender' => 'female',
                'school_name' => 'Sunrise High School',
                'year' => 2018,
                'session' => 'Morning',
                'address' => '456 Birch St',
                'country' => 'Canada',
                'state' => 'British Columbia',
                'city' => 'Vancouver',
                'pincode' => 'V6B 1A1',
                'group' => 'C',
                'other_selection' => 'Option2',
                'status' => 'active',
                'created_at' => Carbon::parse('2025-02-06 11:00:00'),
                'updated_at' => Carbon::parse('2025-02-06 11:00:00'),
            ],
            [
                'email' => 'daniel.brown@example.com',
                'password' => Hash::make('password123'),
                'name' => 'Daniel Brown',
                'enrollment' => 'ENR007',
                'date_of_registration' => '2023-07-15',
                'phone' => '7890123456',
                'dob' => '1996-12-20',
                'gender' => 'male',
                'school_name' => 'Riverdale Academy',
                'year' => 2017,
                'session' => 'Afternoon',
                'address' => '789 Maple St',
                'country' => 'USA',
                'state' => 'Florida',
                'city' => 'Miami',
                'pincode' => '33101',
                'group' => 'A',
                'other_selection' => 'Option3',
                'status' => 'inactive',
                'created_at' => Carbon::parse('2025-02-07 12:15:00'),
                'updated_at' => Carbon::parse('2025-02-07 12:15:00'),
            ],
            [
                'email' => 'olivia.williams@example.com',
                'password' => Hash::make('password123'),
                'name' => 'Olivia Williams',
                'enrollment' => 'ENR008',
                'date_of_registration' => '2023-08-20',
                'phone' => '8901234567',
                'dob' => '2000-04-05',
                'gender' => 'female',
                'school_name' => 'Hillview College',
                'year' => 2022,
                'session' => 'Morning',
                'address' => '654 Walnut St',
                'country' => 'UK',
                'state' => 'England',
                'city' => 'Manchester',
                'pincode' => 'M1 1AA',
                'group' => 'B',
                'other_selection' => 'Option1',
                'status' => 'active',
                'created_at' => Carbon::parse('2025-02-08 09:45:00'),
                'updated_at' => Carbon::parse('2025-02-08 09:45:00'),
            ],
            [
                'email' => 'liam.miller@example.com',
                'password' => Hash::make('password123'),
                'name' => 'Liam Miller',
                'enrollment' => 'ENR009',
                'date_of_registration' => '2023-09-25',
                'phone' => '9012345678',
                'dob' => '1995-11-30',
                'gender' => 'male',
                'school_name' => 'Northview Academy',
                'year' => 2016,
                'session' => 'Evening',
                'address' => '123 Spruce St',
                'country' => 'Canada',
                'state' => 'Quebec',
                'city' => 'Montreal',
                'pincode' => 'H2X 1Y6',
                'group' => 'C',
                'other_selection' => 'Option4',
                'status' => 'inactive',
                'created_at' => Carbon::parse('2025-02-09 14:20:00'),
                'updated_at' => Carbon::parse('2025-02-09 14:20:00'),
            ],
            [
                'email' => 'sophia.taylor@example.com',
                'password' => Hash::make('password123'),
                'name' => 'Sophia Taylor',
                'enrollment' => 'ENR010',
                'date_of_registration' => '2023-10-10',
                'phone' => '0123456789',
                'dob' => '1997-07-22',
                'gender' => 'female',
                'school_name' => 'Brookfield High',
                'year' => 2019,
                'session' => 'Afternoon',
                'address' => '321 Aspen St',
                'country' => 'USA',
                'state' => 'Illinois',
                'city' => 'Chicago',
                'pincode' => '60601',
                'group' => 'A',
                'other_selection' => 'Option3',
                'status' => 'active',
                'created_at' => Carbon::parse('2025-02-10 08:30:00'),
                'updated_at' => Carbon::parse('2025-02-10 08:30:00'),
            ],
        ]);
        
    }
}
